@startuml


class "Sein" as Sein{
key     コードのキーとなる数字とか
label   コードの表記
start   有効開始時
end     有効終了時

time    対象となる時間
now()   現在のSein=headerを返す
at(time) timeのSeinを返す
}
Sein "header　（現在のSein）"-> Sein
Sein "prev　（一つ過去のSein）"-> Sein

@enduml