@startuml

object "利用するクラス" as others
class "和暦 : Enum" as wareki
object "平成 : Enum" as heisei
object "昭和 : Enum" as showa
object "令和 : Enum" as reiwa {
}
object "令和 : Sein" as reiwaA {
visible : true
}
object "令和（改元前） : Sein" as reiwaB {
visible : false
}

others -> wareki
wareki o- heisei
wareki o- showa
wareki o- reiwa
reiwa -> reiwaA
reiwaA -> reiwaB

@enduml