@startuml
scale 960 width
[*] --> 自分のターン

state 自分のターン {
  [*] --> 未選択 : 開始
  未選択 --> 未選択 : 盤タップ
  未選択 --> 選択 : 駒タップ
  選択 --> 選択 : 盤タップ
  選択 --> 未選択: 駒(自分)タップ(未移動)
  選択 --> 行動終了: 駒(自分)タップ(移動済)
  選択 --> 戦闘準備: 駒(敵)タップ
  戦闘準備 --> 選択 : 盤タップ
  戦闘準備 --> 行動終了: 駒(自分)タップ
  戦闘準備 --> 行動終了: 駒(敵)タップ
行動終了 --> 未選択 : 未行動の駒がある
}
行動終了 --> [*] : 全部行動した

@enduml