@startuml
allow_mixing
class "戦場" as Entity {
}

class "升目" as Square {
}

class "英雄ステータス" as Hero {
}

class "英雄(不変)" as BaseHero {
}

Actor "プレイヤー" as Player
Player "操作" -> Entity
Entity  o--> Hero
Entity  o--> Square
Hero <- Square
BaseHero <- Hero
@enduml