@startuml

class "Application" as Viewer {
}
class "組織" as Entity {
    組織ID
    組織名
    有効ユーザ数上限
}

class "ユーザ名簿" as Names {
    ID sequence
    状態（有効/無効）
}

class "ユーザ" as User {
    ユーザID
    ユーザ名
    メールアドレス
    ハッシュ化されたパスワード
}

Viewer --> User
Viewer --> Entity
User --> Entity
Entity o-- Names
User <.. Names

@enduml