@startuml

class 盤{
matrix : 駒[][]
載せる(駒, 座標)
動かす(駒, 座標)
取り除く(駒)
駒を見る(座標)
駒を探す(駒)
}
class 駒{
動かす(座標)
移動範囲を得る(盤)
成る(新能力)
}
class 能力{
移動範囲を得る()
行動範囲を得る()
全ての能力に共通のルール()
}

class 行動駒{
行動(座標)
行動範囲を得る()
}
class 行動盤{
行動範囲matrix : Boolean[][]
行動(駒, 座標)
行動範囲を探索(行動駒)
}

行動盤 -> "載る" 行動駒
行動駒 --> "自分を動かす" 行動盤
駒 -right->  能力
人 -down-> "動かす" 行動駒
人 -down-> "俯瞰する" 行動盤
行動駒 -down-|>  駒
行動盤 -down-|>  盤

@enduml