@startuml

class 盤{
載せる(Any, 座標=Anywhere)
取り除く(Any)
}
class Any{
}
class 座標のある盤{
載せる(駒, 座標)
}
class 駒{
動かす(座標)
}
class デカルト座標系{
}
class 四角座標系{
載せる(四角座標系駒, (X,Y))
}
class 六角座標系{
}

class 四角座標系駒{
X : Int
Y : Int
動かす(X,Y)
}

盤 -o "載る" Any
座標のある盤 -up-|> 盤
駒 -up-|> Any
座標のある盤 -> 駒
四角座標系駒 -up-|> 駒

デカルト座標系 -right-|> 座標のある盤
六角座標系 -right-|> 座標のある盤
四角座標系 -up-|> 座標のある盤
四角座標系 -> 四角座標系駒

@enduml