@startuml

class 盤{
載せる(駒, 座標)
動かす(駒, 座標)
取り除く(駒)
}
class 駒{
動かす(座標)
}
class 能力{
移動範囲を得る()
全ての能力に共通のルール()
}
class 個々の能力{
}
盤 -> "載る" 駒
駒 -left-> "自分を動かす" 盤
'人 -left-> "動かす" 駒
駒 -right->  能力
個々の能力 -up-|>  能力

@enduml