@startuml

class 盤{
matrix : 駒[][]
載せる(駒, 座標)
動かす(駒, 座標)
取り除く(駒)
}
class 地形{
matrix : 地形[][]
}
class 駒{
動かす(座標)
}
class 経路探索駒{
移動可能方向() : Int[]
移動可能か？(侵入状況) : Boolean
何歩使ったか？(侵入状況) : Int
停止可能か？(侵入状況) : Boolean
}
class 能力{
移動範囲を得る()
全ての能力に共通のルール()
}
class 個々の能力{
}
class 移動可能な盤面{
移動matrix : bool[][]
経路を探索する()
}
class 侵入状況{
対象 : 駒?
 歩数 : Int
  侵入角 : Int[]
   地形 : 地形?=null
}


盤 -> "載る" 駒
盤 o-- "天候とかも" 地形
駒 -left-> "自分を動かす" 盤
'人 -left-> "動かす" 駒
駒 -right->  能力
個々の能力 -up-|>  能力
駒 -->"作成"  移動可能な盤面
移動可能な盤面 -up->  盤
経路探索駒 -up-|>  駒
'経路探索駒 --> "探索" 移動可能な盤面
移動可能な盤面 --> "一歩進む" 移動可能な盤面
移動可能な盤面 --> "移動先を提供して判定させる\n移動可能方向を参照" 経路探索駒

@enduml