@startuml

package 戦術サブドメイン {
package 移動モデル {

class 盤{
matrix : 駒[][]
載せる(駒, 座標)
動かす(駒, 座標)
取り除く(駒)
駒を見る(座標)
駒を探す(駒)
}
class 駒{
動かす(座標)
移動範囲を得る(盤)
成る(新能力)
}

abstract 行動駒{
行動を指示する(座標)
行動を実行する(侵入状況)
行動範囲を得る()
}
class 行動盤{
行動範囲matrix : Boolean[][]
行動(駒, 座標)
行動範囲を探索(行動駒)
}
class 侵入状況{
対象 : 駒?
 歩数 : Int
  侵入角 : Int[]
   地形 : 地形?=null
   対象の枡と前後2枡を得る() : 枡[5]
}
}
class そのゲームの行動駒

class そのゲームの地形

}
package 戦闘サブドメイン {
    class キャラクター{
    HP : Int
    他ステータス
    }

    class キャラクター固有の能力

    class 能力{
    移動範囲を得る()
    行動範囲を得る()
    全ての能力に共通のルール()
    }

}


そのゲームの行動駒 "ゲームのルールを実装する" --|> 行動駒
行動盤 -right-> "載る" 行動駒
行動駒 -left-> "自分を動かす" 行動盤
'駒 -right->  能力
'人 "動かす　" --> 行動駒
'人  "俯瞰する" --> 行動盤
行動駒 -down-|>  駒
行動盤 -down-|>  盤
侵入状況 --> "周囲の地形として\n盤を把握" 行動盤
キャラクター --> キャラクター固有の能力
キャラクター固有の能力 --|> 能力
そのゲームの行動駒 -right-> キャラクター
@enduml