@startuml
scale 960 width
[*] --> ゲーム : ゲーム開始

state ゲーム {
  [*] --> ユーザのターン : ユニット配置
  ユーザのターン --> 相手のターン : 全員行動 | ターン終了
  ユーザのターン --> 終了 : 勝利 | 敗北 条件達成
  相手のターン --> ユーザのターン : 全員行動 | ターン終了
  相手のターン --> 終了 : 勝利 | 敗北 条件達成
}
終了 --> [*] : リザルトへ

@enduml