@startuml

object User
class Game{
始める()
中断する()
盤を操作する()
}
class GameUI{
タップする()
ドラッグする()
}
class SimUI{
タップする()
ドラッグする()
}

class 盤{
載せる()
動かす()
取り除く()
}
class Simulator{
盤上のバフを計算する()
駒の戦闘結果を計算する()
}

User "操作\n(Interaction)" --> LibGDX
GameUI --|> LibGDX
GameUI --> Game
Game "操作\n(Operation)" --> 盤
盤 o-- 駒など盤上の要素
SimUI --|> AndroidLib
User --> AndroidLib
SimUI --> Simulator
Simulator "配置の計算"--> 盤
Simulator "戦闘計算"--> 駒など盤上の要素
@enduml