@startuml

object User
class Game{
始める()
中断する()
}
class 盤UI{
タップする()
ドラッグする()
}
class GameUI{
タップする()
ドラッグする()
}
package LibGDX{
class ClickListener
}
class 盤{
載せる()
動かす()
取り除く()
}
class 移動中{
移動元
移動先
}
User "操作\n(Interaction)" --> ClickListener
盤UI --|> ClickListener
GameUI --|> ClickListener
GameUI "操作"--> Game
盤UI "操作\n(Operation)"--> Game
盤UI "操作対象を参照"--> 盤
盤UI --> 移動中
移動中 --> 盤
Game  "操作"--> 盤
Game  "操作"-right-> 移動中
盤 o-- 駒など盤上の要素
@enduml