@startuml

object "利用するクラス" as others
object "年号 : Enum" as nengo
object "令和 : Sein" as reiwaA
object "平成 : Sein" as heisei
object "昭和 : Sein" as showa

others -> nengo
nengo -> reiwaA
reiwaA -> heisei
heisei -> showa

@enduml