@startuml

participant "利用するクラス" as others
participant "年号 : Enum" as nengo
participant "令和 : Sein" as reiwa
participant "平成 : Sein" as heisei
participant "昭和 : Sein" as showa

others -> nengo : 日付指定で問い合わせ
nengo -> reiwa : 期間なら自分を返し、外なら次に回す
reiwa -> heisei : 期間なら自分を返し、外なら次に回す
heisei ->showa : 期間なら自分を返し、外なら次に回す
nengo --> others : 最終的に同じコードだが違う表記が帰る


@enduml