@startuml

abstract class 行動{
val 選択駒 : 駒?
val 戦闘駒 : 駒?
val 移動元 : 枡?
val 移動先 : 枡?
駒タップ(対象駒 : 駒, 対象枡 : 枡) : 行動
盤タップ(対象枡 : 枡) : 行動
}

class 未選択{

}
class 選択{
val 選択駒 : 駒
val 戦闘駒 : 駒?
val 移動元 : 枡
val 移動先 : 枡
}
class 戦闘準備{
val 選択駒 : 駒
val 戦闘駒 : 駒
val 移動元 : 枡
val 移動先 : 枡
}
行動 <|-- 未選択
行動 <|-- 選択
行動 <|-- 戦闘準備

@enduml